version: '3.4'

services:
  produtoapi:
    image: produtoapi
    build:
      context: .
      dockerfile: ProdutoAPI2/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__SqlServerConnection=Server=DESKTOP-02N990P;Database=db_Produtos;User Id=usr_teste;Password=teste123;

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=teste123
    ports:
      - "1433:1433"
